# TCL File Generated by Component Editor 23.1
# Sun Dec 08 11:12:45 MST 2024
# DO NOT MODIFY


# 
# lcd "lcd" v1.0
#  2024.12.08.11:12:45
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module lcd
# 
set_module_property DESCRIPTION ""
set_module_property NAME lcd
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME lcd
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL lcd
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file lcd.vhd VHDL PATH ../../hdl/bb-calc/lcd.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_2
# 
add_interface avalon_slave_2 avalon end
set_interface_property avalon_slave_2 addressUnits WORDS
set_interface_property avalon_slave_2 associatedClock clk
set_interface_property avalon_slave_2 associatedReset rst
set_interface_property avalon_slave_2 bitsPerSymbol 8
set_interface_property avalon_slave_2 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_2 burstcountUnits WORDS
set_interface_property avalon_slave_2 explicitAddressSpan 0
set_interface_property avalon_slave_2 holdTime 0
set_interface_property avalon_slave_2 linewrapBursts false
set_interface_property avalon_slave_2 maximumPendingReadTransactions 0
set_interface_property avalon_slave_2 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_2 readLatency 0
set_interface_property avalon_slave_2 readWaitTime 1
set_interface_property avalon_slave_2 setupTime 0
set_interface_property avalon_slave_2 timingUnits Cycles
set_interface_property avalon_slave_2 writeWaitTime 0
set_interface_property avalon_slave_2 ENABLED true
set_interface_property avalon_slave_2 EXPORT_OF ""
set_interface_property avalon_slave_2 PORT_NAME_MAP ""
set_interface_property avalon_slave_2 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_2 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_2 avs_read read Input 1
add_interface_port avalon_slave_2 avs_write write Input 1
add_interface_port avalon_slave_2 avs_address address Input 2
add_interface_port avalon_slave_2 avs_readdata readdata Output 32
add_interface_port avalon_slave_2 avs_writedata writedata Input 32
set_interface_assignment avalon_slave_2 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_2 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_2 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_2 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst reset Input 1


# 
# connection point export
# 
add_interface export conduit end
set_interface_property export associatedClock clk
set_interface_property export associatedReset ""
set_interface_property export ENABLED true
set_interface_property export EXPORT_OF ""
set_interface_property export PORT_NAME_MAP ""
set_interface_property export CMSIS_SVD_VARIABLES ""
set_interface_property export SVD_ADDRESS_GROUP ""

add_interface_port export ctl ctl Output 3
add_interface_port export data data Output 8

